version: "3.4"
services:
  printserver:
    build: .
    restart: unless-stopped
    environment:
      PRINTER_ID: Paperless_Printer3 # ID (No spaces)
      PRINTER_NAME: Paperless Printer3 # Name of printer
      HOSTNAME: '192.168.123.252:631' # Use static IP (below) or hostname if you have one
      OUTPUT_SUBPATH: 'vprint' # Subpath in /mnt/output/
    networks:
      - cups-vlan
    volumes:
      - /volume1/docker/printer:/mnt/output
    ports:
      - 631:631 # Expose HTTP server

networks:
  cups-vlan:
    driver: macvlan
    driver_opts:
      parent: eth0 # Update as necessary
    ipam:
      config:
        - subnet: "192.168.123.0/24"
          ip_range: "192.168.123.252/32" #static IP
          gateway: "192.168.123.1"
